# -*- coding: utf-8 -*-
"""Crypto Tracker Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dru6DCFuVxDgJ29ccZoPoNYtOLh9avuU
"""


import streamlit as st

main_page = st.Page("main_page.py", title = "Main Page", icon = '📊')
page_2 = st.Page("page_2.py", title = 'All Coins', icon = '🪙')

pg = st.navigation([main_page, page_2])
pg.run()


