# -*- coding: utf-8 -*-
"""Crypto Tracker Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dru6DCFuVxDgJ29ccZoPoNYtOLh9avuU
"""

import streamlit as st
coinDict = {}
def create_coin_table():
  import requests
  coins = ['bitcoin','ethereum','dogecoin','usd-coin','weth','tether','ripple','tron','solana','zcash']#later find out which coins are really what people are looking at

  api_key = st.secrets['api_key']
  url = 'https://api.coingecko.com/api/v3/simple/price'
  headers = {
      api_key
  }

  params = {
      'ids': ','.join(coins),
      'vs_currencies': 'usd',
      'include_market_cap': 'true',
      'include_24hr_change': 'true',
      "include_24hr_vol": 'true'

  }

  response = requests.get(url, params = params)
  data = response.json()

  for coin in coins:
    if coin in data:
      price = data[coin]['usd']
      cap = data[coin]['usd_market_cap']
      dailyChange = data[coin]['usd_24h_change']
      dailyVol = data[coin]['usd_24h_vol']

      coinDict[coin] = [price,cap,dailyChange,dailyVol]
    else:
      st.warning(coin + ' coin not found')

def display_coin_table():
  import pandas as pd

  df = pd.DataFrame.from_dict(coinDict,orient = 'index', columns = ['Current Price',"Market Cap",'24 Hour Change','24 Hour Volume'])
  df = df.reset_index().rename(columns={'index': 'Name'})

  #Display
  st.dataframe(df.style.format({"Current Price": "{:,.2f}", "Market Cap": "${:,.2f}", "24 Hour Change": "{:.2f}","24 Hour Volume": "${:,.2f}"}).set_table_styles([
      {'selector': 'th',
      'props': [('font-weight', 'bold'),
                ('text-align', 'center')]}
  ]))

st.title('Crypto Tracker')
create_coin_table()
display_coin_table()